window.CONFIG = Object.freeze({
  strategyVersion: "V2.1",
  buyEngineV2: Object.freeze({
    status: "HEURISTIC · NOT BACKTEST OPTIMIZED",
    deadband: 1,
    gapFillRates: Object.freeze({ large: 0.1, medium: 0.12, small: 0.15 }),
    gapBands: Object.freeze({ large: 20, medium: 10 }),
    trendFactors: Object.freeze({
      strongRise: 1.15,
      rise: 1.1,
      stable: 1,
      mildFall: 0.85,
      clearFall: 0.6,
      strongRiseAt: 2,
      riseAt: 0.5,
      mildFallAt: -2,
    }),
    marketFactors: Object.freeze({ favorable: 1.15, normal: 1, hot: 0.8 }),
    minDynamicScale: 1,
    maxDynamicScale: 5,
    minETFExecution: 500,
    minDailyExecution: 5000,
    amountTolerance: 2,
    premium: Object.freeze({
      nav: 0.1,
      normal: 0.5,
      urgent: 1.25,
      hardCap: 2.5,
    }),
    concentration: Object.freeze({
      singleSoft: 0.1,
      singleHard: 0.15,
      groupSoft: 0.25,
      groupHard: 0.4,
      leveragedSoft: 0.08,
      leveragedHard: 0.12,
      reducedFactor: 0.5,
    }),
    extreme: Object.freeze({
      activateScore: 6,
      mediumScore: 7,
      highScore: 8,
      maxScore: 9,
      fillRates: Object.freeze({ low: 0.3, medium: 0.5, high: 0.7, max: 0.9 }),
      cnn: 20,
      arkTarget: 80,
      arkRise1D: 1,
      rsi: 30,
      bias20D: -5,
      percentile: 20,
      drawdown: -5,
      margin: 150,
      vix: 30,
    }),
    storageKeys: Object.freeze({
      pending: "arkStrategyLab.execution.pending.v2",
      confirmedArk: "arkStrategyLab.arkDaily.v2",
    }),
  }),
  imageImport: Object.freeze({
    provider: "GeminiVisionProvider",
    maxScreenshots: 5,
    visionEndpoint:
      "https://script.google.com/macros/s/AKfycby_pcukAJMHn-Z_yzeCPqDc35QbSotwAQX0GrMl9i6uSj-JFz_X4DGHxkiSgM7zrK7BNg/exec",
    requireUserConfirmation: true,
  }),
  rebalance: {
    strategyVersion: "REBALANCE_V1.0",
    status: "HEURISTIC · NOT BACKTEST OPTIMIZED",
    usCnnBands: [
      { max: 25, factor: 0.6, label: "極度恐懼" },
      { max: 40, factor: 0.8, label: "恐懼" },
      { max: 60, factor: 1, label: "中性" },
      { max: 75, factor: 1.15, label: "偏熱" },
      { max: 100, factor: 1.3, label: "過熱" },
    ],
    usSignals: {
      rsiCold: 30,
      rsiHot: 70,
      biasCold: -5,
      biasHot: 5,
      percentileCold: 20,
      percentileHot: 85,
      returnCold: -4,
      returnHot: 6,
      modifierStep: 0.05,
      minFactor: 0.5,
      maxFactor: 1.4,
    },
    taiwan: {
      rsiCold: 30,
      rsiWarm: 60,
      rsiHot: 70,
      biasCold: -5,
      biasWarm: 3,
      biasHot: 6,
      percentileCold: 0.2,
      percentileWarm: 0.7,
      percentileHot: 0.85,
      returnCold: -4,
      returnWarm: 3,
      returnHot: 6,
      marginWarm: 180,
      marginHot: 200,
      scoreCold: -2,
      scoreWarm: 2,
      scoreHot: 4,
      scoreExtreme: 6,
      minFactor: 0.6,
      maxFactor: 1.4,
      step: 0.1,
    },
    daysOutBands: [
      { max: 0, points: 0 },
      { max: 2, points: 3 },
      { max: 5, points: 9 },
      { max: 10, points: 15 },
      { max: Infinity, points: 20 },
    ],
    concentration: {
      singleWarm: 0.12,
      singleHigh: 0.2,
      groupWarm: 0.25,
      groupHigh: 0.4,
      extremeSingle: 0.3,
      extremeGroup: 0.5,
    },
    priority: {
      base: 20,
      riskOff: 12,
      strongExit: 14,
      arkOut: 4,
      arkRankWeak: 3,
      arkRankWeakAfter: 8,
      presenceWeak: 5,
      singleWarm: 7,
      singleHigh: 14,
      groupWarm: 8,
      groupHigh: 16,
      leverage: 5,
      leverageCluster: 12,
      profitMax: 5,
      profitPerPercent: 0.1,
      smallCleanup: 3,
      smallPositionRatio: 0.01,
      inArkDiscount: 5,
      levels: { watch: 25, medium: 45, high: 65, veryHigh: 80 },
    },
    performance: {
      enabled: true,
      weights: { ytd: 0.25, oneYear: 0.35, threeYearAnnualized: 0.4 },
      weakMaxPoints: 6,
      strongMaxDiscount: 4,
      minimumPeers: 2,
      cacheHours: 12,
    },
    optimizer: {
      maxHoldings: 40,
      maxSteps: 200000,
      minimumPartialShares: 1,
      defaultOddLot: true,
      defaultFullExit: false,
      globalFactor: 0.95,
    },
    storageKeys: {
      state: "arkStrategyLab.rebalance.state.v1",
      history: "arkStrategyLab.rebalance.history.v1",
      performance: "arkStrategyLab.rebalance.performance.v1",
    },
  },
  deadBand: 1,
  buyWatchMaxGap: 5,
  defensiveAccumulationGap: 20,
  rapidDropPause: 6,
  prolongedDropPause: 12,
  distributionDrawdown: 2,
  confirmedDistributionDrawdown: 5,
  riskOffDrawdown: 8,
  sellFillDistribution: 0.15,
  sellFillConfirmed: 0.25,
  sellFillRiskOff: 0.5,
  maxBuyMultiplier: 5.0,
  minInitialBuildMultiplier: 1.8,
  arkWaterLevels: Object.freeze({
    year: 2026,
    min: 61.6,
    lowerDecile: 64.3,
    upperDecile: 80.3,
    max: 87.4,
  }),
  historyLimit: 60,
  googleSheets: {
    enabled: true,
    webAppUrl:
      "https://script.google.com/macros/s/AKfycbx_hrLGj3Hhezed8EpAX_INeZxbvRl4xW6AcEbjVu6VeWGTJz-f1zgQLl88b9FgXkQk/exec",
    sheetName: "紀錄",
    spreadsheetId: "1YlZu_ztxjwjdBkld25l4H4WdaBb94E8u3r02-ew3NfA",
    gid: "671589303",
    syncHourTaipei: 8,
  },
  storageKeys: {
    state: "arkStrategyLab.state.v1",
    history: "arkStrategyLab.history.v1",
    etfs: "arkStrategyLab.etfs.v1",
    cache: "arkStrategyLab.centralCache.v2",
    visionToken: "arkStrategyLab.visionToken.v1",
  },
});
