window.CONFIG = Object.freeze({
  strategyVersion: "BUY_ENGINE_V2.0",
  buyEngineV2: Object.freeze({
    status: "HEURISTIC · NOT BACKTEST OPTIMIZED",
    deadband: 1,
    gapFillRates: Object.freeze({large:.10,medium:.12,small:.15}),
    gapBands: Object.freeze({large:20,medium:10}),
    trendFactors: Object.freeze({strongRise:1.15,rise:1.10,stable:1,mildFall:.85,clearFall:.60,strongRiseAt:2,riseAt:.5,mildFallAt:-2}),
    marketFactors: Object.freeze({favorable:1.15,normal:1,hot:.80}),
    minDynamicScale: 1,
    maxDynamicScale: 5,
    minETFExecution: 500,
    minDailyExecution: 5000,
    amountTolerance: 2,
    premium: Object.freeze({nav:.10,normal:.50,urgent:1.25,hardCap:2.50}),
    concentration: Object.freeze({singleSoft:.10,singleHard:.15,groupSoft:.25,groupHard:.40,leveragedSoft:.08,leveragedHard:.12,reducedFactor:.50}),
    extreme: Object.freeze({activateScore:6,mediumScore:7,highScore:8,maxScore:9,fillRates:Object.freeze({low:.30,medium:.50,high:.70,max:.90}),cnn:20,arkTarget:80,arkRise1D:1,rsi:30,bias20D:-5,percentile:20,drawdown:-5,margin:150,vix:30}),
    storageKeys: Object.freeze({pending:"arkStrategyLab.execution.pending.v2",confirmedArk:"arkStrategyLab.arkDaily.v2"})
  }),
  imageImport: Object.freeze({provider:"GeminiVisionProvider",maxScreenshots:5,visionEndpoint:"",requireUserConfirmation:true}),
  rebalance: {
    strategyVersion: "REBALANCE_V1.0", status: "HEURISTIC · NOT BACKTEST OPTIMIZED",
    usCnnBands: [{max:25,factor:.60,label:"極度恐懼"},{max:40,factor:.80,label:"恐懼"},{max:60,factor:1,label:"中性"},{max:75,factor:1.15,label:"偏熱"},{max:100,factor:1.30,label:"過熱"}],
    usSignals:{rsiCold:30,rsiHot:70,biasCold:-5,biasHot:5,percentileCold:20,percentileHot:85,returnCold:-4,returnHot:6,modifierStep:.05,minFactor:.5,maxFactor:1.4},
    taiwan: {rsiCold:30,rsiWarm:60,rsiHot:70,biasCold:-5,biasWarm:3,biasHot:6,percentileCold:.2,percentileWarm:.7,percentileHot:.85,returnCold:-4,returnWarm:3,returnHot:6,marginWarm:180,marginHot:200,scoreCold:-2,scoreWarm:2,scoreHot:4,scoreExtreme:6,minFactor:.6,maxFactor:1.4,step:.1},
    daysOutBands:[{max:0,points:0},{max:2,points:3},{max:5,points:9},{max:10,points:15},{max:Infinity,points:20}],
    concentration:{singleWarm:.12,singleHigh:.20,groupWarm:.25,groupHigh:.40,extremeSingle:.30,extremeGroup:.50},
    priority:{base:20,riskOff:12,strongExit:14,arkOut:4,arkRankWeak:3,arkRankWeakAfter:8,presenceWeak:5,singleWarm:7,singleHigh:14,groupWarm:8,groupHigh:16,leverage:5,leverageCluster:12,profitMax:5,profitPerPercent:.1,smallCleanup:3,smallPositionRatio:.01,inArkDiscount:5,levels:{watch:25,medium:45,high:65,veryHigh:80}},
    optimizer:{maxHoldings:40,maxSteps:200000,minimumPartialShares:1,defaultOddLot:true,defaultFullExit:false,globalFactor:.95},
    storageKeys:{state:"arkStrategyLab.rebalance.state.v1",history:"arkStrategyLab.rebalance.history.v1"}
  },
  deadBand: 1,
  buyWatchMaxGap: 5,
  defensiveAccumulationGap: 20,
  rapidDropPause: 6,
  prolongedDropPause: 12,
  distributionDrawdown: 2,
  confirmedDistributionDrawdown: 5,
  riskOffDrawdown: 8,
  sellFillDistribution: 0.15,
  sellFillConfirmed: 0.25,
  sellFillRiskOff: 0.50,
  maxBuyMultiplier: 3.0,
  minInitialBuildMultiplier: 1.8,
  historyLimit: 60,
  googleSheets: {
    enabled: true,
    webAppUrl: "https://script.google.com/macros/s/AKfycbx_hrLGj3Hhezed8EpAX_INeZxbvRl4xW6AcEbjVu6VeWGTJz-f1zgQLl88b9FgXkQk/exec",
    sheetName: "紀錄",
    spreadsheetId: "1YlZu_ztxjwjdBkld25l4H4WdaBb94E8u3r02-ew3NfA",
    gid: "671589303",
    syncHourTaipei: 8
  },
  storageKeys: {
    state: "arkStrategyLab.state.v1",
    history: "arkStrategyLab.history.v1",
    etfs: "arkStrategyLab.etfs.v1",
    cache: "arkStrategyLab.centralCache.v2",
    visionToken: "arkStrategyLab.visionToken.v1"
  }
});
